### ISSUE TITLE
Default behavior from nvim-cmp

### ISSUE THREAD

**Issue by zjp-CN** [zjp-CN/nvim-cmp-lsp-rs#1]
```toml
[package]
name = "xxx"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
ratatui = "0.26"
```

```rust
#![allow(unused)]
use ratatui::prelude::*;

fn main() {
    let s = S {
        s: String::from("hello"),
    };
    // type `s.` and you'll see random completion list
}

struct S {
    s: String,
}

impl S {
    pub fn render(&self, buf: &mut Buffer) {}

    pub fn zzzz(&self) {}
}

impl Widget for &S {
    fn render(self, area: Rect, buf: &mut Buffer) {}
}
```

![](https://github.com/zjp-CN/nvim-cmp-lsp-rs/assets/25300418/e3b00e5e-7aa2-4a46-8704-7351f24d7ded)

Radomness here means you'll see very puzzling, unpredictable and counterintuitive list when somthing changes, when you even add a method without closing the current file!
